apiVersion: apps/v1
kind: Deployment
metadata:
  name: cesi-eats-app
  labels:
    app: cesi-eats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cesi-eats
  template:
    metadata:
      labels:
        app: cesi-eats
    spec:
      containers:
        # Backend services
        - name: auth-service
          image: ghcr.io/Arenz2001/cesi-eats/auth-service:latest
          ports:
            - containerPort: 3004
              name: auth-http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/cesi-eats"
            - name: JWT_SECRET
              value: "your-jwt-secret"
            - name: JWT_EXPIRES_IN
              value: "1d"
            - name: PORT
              value: "3004"

        - name: customer-service
          image: ghcr.io/Arenz2001/cesi-eats/customer-service:latest
          ports:
            - containerPort: 3001
              name: customer-http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/cesi-eats"
            - name: PORT
              value: "3001"

        - name: order-service
          image: ghcr.io/Arenz2001/cesi-eats/order-service:latest
          ports:
            - containerPort: 3003
              name: order-http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/cesi-eats"
            - name: PORT
              value: "3003"

        - name: restaurant-service
          image: ghcr.io/Arenz2001/cesi-eats/restaurant-service:latest
          ports:
            - containerPort: 3002
              name: restaurant-http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/cesi-eats"
            - name: PORT
              value: "3002"

        - name: delivery-service
          image: ghcr.io/Arenz2001/cesi-eats/delivery-service:latest
          ports:
            - containerPort: 3005
              name: delivery-http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/cesi-eats"
            - name: PORT
              value: "3005"

        - name: third-party-dev-service
          image: ghcr.io/Arenz2001/cesi-eats/third-party-dev-service:latest
          ports:
            - containerPort: 3006
              name: tps-http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/cesi-eats"
            - name: PORT
              value: "3006"

        # Frontend applications
        - name: customer-app
          image: ghcr.io/Arenz2001/cesi-eats/customer-app:latest
          ports:
            - containerPort: 4000
              name: customer-app-http
          env:
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: "http://localhost:3004/"
            - name: NEXT_PUBLIC_CUSTOMER_API_URL
              value: "http://localhost:3001/"
            - name: NEXT_PUBLIC_RESTAURANT_API_URL
              value: "http://localhost:3002/"
            - name: NEXT_PUBLIC_ORDER_API_URL
              value: "http://localhost:3003/"
            - name: NEXT_PUBLIC_DELIVERY_API_URL
              value: "http://localhost:3005/"
            - name: NEXT_PUBLIC_THIRD_PARTY_API_URL
              value: "http://localhost:3006"

        - name: delivery-app
          image: ghcr.io/Arenz2001/cesi-eats/delivery-app:latest
          ports:
            - containerPort: 4001
              name: delivery-app-http
          env:
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: "http://localhost:3004/"
            - name: NEXT_PUBLIC_CUSTOMER_API_URL
              value: "http://localhost:3001/"
            - name: NEXT_PUBLIC_RESTAURANT_API_URL
              value: "http://localhost:3002/"
            - name: NEXT_PUBLIC_ORDER_API_URL
              value: "http://localhost:3003/"
            - name: NEXT_PUBLIC_DELIVERY_API_URL
              value: "http://localhost:3005/"
            - name: NEXT_PUBLIC_THIRD_PARTY_API_URL
              value: "http://localhost:3006"

        - name: commercial-app
          image: ghcr.io/Arenz2001/cesi-eats/commercial-app:latest
          ports:
            - containerPort: 4002
              name: commercial-app-http
          env:
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: "http://localhost:3004/"
            - name: NEXT_PUBLIC_CUSTOMER_API_URL
              value: "http://localhost:3001/"
            - name: NEXT_PUBLIC_RESTAURANT_API_URL
              value: "http://localhost:3002/"
            - name: NEXT_PUBLIC_ORDER_API_URL
              value: "http://localhost:3003/"
            - name: NEXT_PUBLIC_DELIVERY_API_URL
              value: "http://localhost:3005/"
            - name: NEXT_PUBLIC_THIRD_PARTY_API_URL
              value: "http://localhost:3006"

        - name: restaurant-app
          image: ghcr.io/Arenz2001/cesi-eats/restaurant-app:latest
          ports:
            - containerPort: 4003
              name: restaurant-app-http
          env:
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: "http://localhost:3004/"
            - name: NEXT_PUBLIC_CUSTOMER_API_URL
              value: "http://localhost:3001/"
            - name: NEXT_PUBLIC_RESTAURANT_API_URL
              value: "http://localhost:3002/"
            - name: NEXT_PUBLIC_ORDER_API_URL
              value: "http://localhost:3003/"
            - name: NEXT_PUBLIC_DELIVERY_API_URL
              value: "http://localhost:3005/"
            - name: NEXT_PUBLIC_THIRD_PARTY_API_URL
              value: "http://localhost:3006"

        - name: third-party-dev-app
          image: ghcr.io/Arenz2001/cesi-eats/third-party-dev-app:latest
          ports:
            - containerPort: 4004
              name: tpd-app-http
          env:
            - name: NEXT_PUBLIC_AUTH_API_URL
              value: "http://localhost:3004/"
            - name: NEXT_PUBLIC_CUSTOMER_API_URL
              value: "http://localhost:3001/"
            - name: NEXT_PUBLIC_RESTAURANT_API_URL
              value: "http://localhost:3002/"
            - name: NEXT_PUBLIC_ORDER_API_URL
              value: "http://localhost:3003/"
            - name: NEXT_PUBLIC_DELIVERY_API_URL
              value: "http://localhost:3005/"
            - name: NEXT_PUBLIC_THIRD_PARTY_API_URL
              value: "http://localhost:3006"

        # Shared MongoDB instance
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db

      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc-shared

---
# Services for backend
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3004
      nodePort: 30004

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 30003

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3005
      nodePort: 30005

---
apiVersion: v1
kind: Service
metadata:
  name: third-party-dev-service
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3006
      nodePort: 30006

# Services for frontend
---
apiVersion: v1
kind: Service
metadata:
  name: customer-app
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-app
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4001
      nodePort: 31001

---
apiVersion: v1
kind: Service
metadata:
  name: commercial-app
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4002
      nodePort: 31002

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-app
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4003
      nodePort: 31003

---
apiVersion: v1
kind: Service
metadata:
  name: third-party-dev-app
spec:
  type: NodePort
  selector:
    app: cesi-eats
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4004
      nodePort: 31004

# Shared MongoDB storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-shared
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb-cesi-eats
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
