apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  labels:
    app: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: ghcr.io/Arenz2001/cesi-eats/restaurant-service:latest
          ports:
            - containerPort: 30001
              name: http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/restaurant"
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30001
      nodePort: 30001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-restaurant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
