apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-party-dev-service
  labels:
    app: third-party-dev-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: third-party-dev-service
  template:
    metadata:
      labels:
        app: third-party-dev-service
    spec:
      containers:
        - name: third-party-dev-service
          image: ghcr.io/Arenz2001/cesi-eats/third-party-dev-service:latest
          ports:
            - containerPort: 30012
              name: http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/third-party-dev"
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: third-party-dev-service
spec:
  type: NodePort
  selector:
    app: third-party-dev-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30012
      nodePort: 30012
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-third-party-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
