apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: ghcr.io/Arenz2001/cesi-eats/customer-service:latest
          ports:
            - containerPort: 3003
              name: http
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/customer"
            - name: PORT
              value: "3003"
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 30005
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-customer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
