apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  labels:
    app: customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: ghcr.io/Arenz2001/cesi-eats/customer-app:latest
          ports:
            - containerPort: 30010
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: customer-app
spec:
  type: NodePort
  selector:
    app: customer-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30010
      nodePort: 30010
