name: API Gateway CI/CD

on:
  push:
    branches:
      - main
      - feature/api-gateway
    paths:
      - "apps/api-gateway/**"
      - "k8s/api-gateway/**"
      - ".github/workflows/api-gateway.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: arenz2001/cesieats/api-gateway

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: k8s/api-gateway
          file: k8s/api-gateway/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          chmod 600 kubeconfig.yaml
          export KUBECONFIG="$PWD/kubeconfig.yaml"
          echo "=== Kubectl config ==="
          kubectl config view --raw
          echo "=== Testing connection ==="
          kubectl cluster-info

      - name: Create or update deployment
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          kubectl delete service api-gateway --ignore-not-found
          sed -i "s|ghcr.io/[Aa]renz2001/cesieats/api-gateway:[^ ]*|ghcr.io/arenz2001/cesieats/api-gateway:sha-${{ github.sha }}|g" k8s/api-gateway/deployment.yaml
          kubectl apply -f k8s/api-gateway/deployment.yaml
          kubectl rollout status deployment/api-gateway

      - name: Debug deployment
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          echo "Checking deployment status..."
          kubectl get deployment api-gateway -o yaml
          echo "\nChecking pods..."
          kubectl get pods
          echo "\nChecking service..."
          kubectl get service api-gateway
          echo "\nDescribing pods..."
          kubectl describe pods -l app=api-gateway
