# .github/workflows/auth-service.yml
name: Auth Service CI/CD

on:
  push:
    paths:
      - 'apps/backend/auth-service/**'
      - '.github/workflows/auth-service.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/auth-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend/auth-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          # Décode le kubeconfig
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          
          # Affiche le contenu (attention aux données sensibles)
          echo "=== Kubeconfig content ==="
          grep "server:" kubeconfig.yaml
          
          # Configure kubectl
          export KUBECONFIG=kubeconfig.yaml
          
          # Test la connexion
          kubectl config view --minify | grep server

          # Vérifie que kubectl utilise le bon fichier
          echo "KUBECONFIG=$KUBECONFIG"

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/auth-service \
            auth-service=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}